language: "perl"
perl:
  - "5.18"
  - 5.20

#before_install:
#    - sudo apt-get libxml2-dev zlib1g-dev

install:
    - cpanm --installdeps --notest Treex::Core
    - cpanm --notest URI::Find::Schemeless PerlIO::gzip Text::Iconv AI::MaxEntropy Cache::Memcached Email::Find XML::Twig String::Util String::Diff List::Pairwise MooseX::Role::AttributeOverride YAML::Tiny Graph Tree::Trie Text::Brew App::whichpm
    - cpanm Lingua::Interset

script:
    - "prove -Ilib -r lib/Treex/Core"

after_success:
    - echo $CC
    - clang --version
    - g++ --version
    - cpanm -v Ufal::MorphoDiTa # just for debugging
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-4.8 g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - g++ --version
    - cpanm -v Ufal::MorphoDiTa
    - CC=g++ cpanm -v Ufal::MorphoDiTa
    - CC=clang cpanm -v Ufal::MorphoDiTa

after_failure:
    - cpanm -v Ufal::MorphoDiTa # just for debugging
