language: "perl"
perl:
  - "5.18"

#before_install:
#    - sudo apt-get libxml2-dev zlib1g-dev
#    - cpanm Test::Pod # optional dependency

install:
    - cpanm -v --installdeps --notest Treex::Core

script: "prove -Ilib -r lib/Treex/Core"