language: "perl"
perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

#before_install:
#    - sudo apt-get libxml2-dev zlib1g-dev
#    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#    - sudo apt-get update -qq
#    - sudo apt-get install -qq gcc-4.8 g++-4.8
#    - CC=g++-4.8 cpanm -v Ufal::MorphoDiTa

install:
    - export PERL5LIB=`pwd`/lib; export PATH=`pwd`/bin:$PATH;
    #- cpanm --installdeps --notest Treex::Core
    #- cpanm --notest URI::Find::Schemeless PerlIO::gzip Text::Iconv AI::MaxEntropy Cache::Memcached Email::Find XML::Twig String::Util String::Diff List::Pairwise MooseX::Role::AttributeOverride YAML::Tiny Graph Tree::Trie Text::Brew App::whichpm
    #- cpanm Lingua::Interset
    #- CC=g++-4.8 cpanm -v Ufal::NameTag

script:
    #- prove -r lib/Treex/Core
    #- lib/Treex/Tool/Tagger/t/morphodita.t
    #- lib/Treex/Tool/NER/t/nametag_en.t

after_success:
    - clang -v
    - CC=clang cpanm Ufal::MorphoDiTa
    - lib/Treex/Tool/Tagger/t/morphodita.t
    - clang++ -v
    - CC=clang++ cpanm -v Ufal::NameTag
    - CC=clang cpanm -v Ufal::NameTag

